title: "Replication Package for CoLiCo"
description: "<b>Replication Package for Our Paper:</b><br>Inferring Analogical API Methods based on Large-Scale Analysis of Third-Party Libraries Using Knowledge Graph Embedding"
theme: jekyll-theme-cayman